baseURL: https://jared-max-bloom.netlify.app/
languageCode: en-us
title: Jared Bloom
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Musings & Learnings
    title: Jared Bloom MFA
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Gloucester Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: bloom.jared@yahoo.com
        title: Email
    enable: yes
    phone:
      - phone: +1 (646) 291-2550
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
      #  label: Twitter
       # url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/jared.bloom.9
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/jmaxbloom/
      - icon: fa-github
        label: GitHub
        url: https://github.com/jmaxbloom
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/jared-max-bloom
  image: ''
  name: Jared Bloom
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Resume
        url: blogs/CV
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
      #  url: blogs/ipsum
      #- name: About Me
      #  url: elements.html
    menu: Menu
    #subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: My Journey
        title: Holiday Reflections
        url: blogs/yk
      - image: books.jpg
        subtitle: Great Works
        title: Book Club
        url: blogs/literature
      - image: Climate.jpg
        subtitle: Party Politics and Climate Chagne
        title: The Politics of Global Warming
        url: blogs/GOP
      - image: investing.jpg
        subtitle: A year of investing
        title: Portfolio Milestones
        url: blogs/invests
      - image: shock.jpg
        #subtitle:
        title: Culture Shock
        url: blogs/culture
      - image: HK.jpg
        subtitle: Approximating Hong Kong Airbnb Prices
        title: A vacation to Asia
        url: blogs/hk
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Jared bloom is a student at LBS in the MFA program.
      \r\n    Jared graduated with an economics degree from UC Berkeley.\r\n    
      He is an out and proud gay man from the suburbs of New York City with an interest in investing\r\n    Nullam et orci eu lorem consequat tincidunt.
      Jared has worked in many different areas of financial services and is excited to learn more.\r\n    "
    title: Quick Intro
    url: blogs
